In [14]:
import pandas as pd
import numpy as np

In [4]:
matriz = pd.read_csv('aluguel_residencial_sem_outliers.csv', sep = ';')

In [5]:
matriz

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU,Valor Bruto,Media m2,Tipo agregado
0,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0,1210.0,80.67,Apartamento
1,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,0.0,1030.0,21.46,Apartamento
2,Apartamento,Vista Alegre,3,1,0,70,1200.0,0.0,0.0,1200.0,17.14,Apartamento
3,Apartamento,Cachambi,2,0,0,50,1300.0,301.0,17.0,1618.0,32.36,Apartamento
4,Apartamento,Centro,1,0,0,36,1200.0,0.0,0.0,1200.0,33.33,Apartamento
...,...,...,...,...,...,...,...,...,...,...,...,...
20818,Sítio,Lagoa,6,0,2,750,15000.0,0.0,1800.0,16800.0,22.40,Apartamento
20819,Sítio,Vargem Pequena,2,0,0,2900,8000.0,0.0,22344.0,30344.0,10.46,Apartamento
20820,Sítio,Camorim,8,0,7,32000,15000.0,0.0,0.0,15000.0,0.47,Apartamento
20821,Sítio,Camorim,8,0,7,42000,20000.0,0.0,0.0,20000.0,0.48,Apartamento
20822,Sítio,Camorim,8,0,7,32000,15000.0,0.0,0.0,15000.0,0.47,Apartamento

In [9]:
matriz['Bairro'].drop_duplicates()

0                Centro
1          Higienópolis
2          Vista Alegre
3              Cachambi
5                Grajaú
              ...
18055           Paquetá
18175    Senador Camará
19216        Cachamorra
19493      Rio da Prata
19832      Vila Militar
Name: Bairro, Length: 153, dtype: object

In [12]:
x = matriz['Bairro'].unique()

In [16]:
len(x)

153